name: pocketcasts-readme
author: Mahesh Rijal
description: Updates your README with recently listened podcasts from pocketcasts.

inputs:
  POCKETCASTS_EMAIL:
    description: Pocketcasts Email Address
    required: true

  POCKETCASTS_PASSWORD:
    description: Pocketcasts password
    required: true

runs:
  using: composite
  steps:
    - id: update-podcasts
      run: go run main.go
      shell: bash

branding:
  icon: headphones
  color: blue
